
// SESSION

export const AUTH_USER = "AUTH/AUTH_USER"
export const LOGOUT_USER = "AUTH/LOGOUT_USER"
export const SET_AUTH_ERROR = "AUTH/SET_AUTH_ERROR"
export const CLEAR_AUTH_ERRORS = "AUTH/CLEAR_AUTH_ERRORS"

// COURSES

export const CLEAN_UP_COURSES = "COURSES/CLEAN_UP_COURSES"
export const CLEAN_UP_DETAILS = "COURSES/CLEAN_UP_DETAILS"
export const GET_COURSE_DETAILS = "COURSES/GET_COURSE_DETAILS"
export const GET_ALL_COURSES = "COURSES/GET_ALL_COURSES"
export const CLEAN_UP_ALL_COURSES = "COURSES/CLEAN_UP_ALL_COURSES"

// COURSE

export const COMMENT_COURSE = "COURSE/COMMENT_COURSE"

// CATEGORIES

export const GET_CATEGORIES = "CATEGORIES/GET_CATEGORIES"
export const SPLIT_BY_CATEGIRES = "CATEGORIES/SPLIT_BY_CATEGIRES"

// PROFILE

export const EDIT_PROFILE = "PROFILE/EDIT_PROFILE"